Drive
SciBorgs/Hydrogen pull request #21
Opened 2024-01-17 21:00 UTC by kishan243

2024-01-17 21:02 UTC, kishan243 commented
Drive pull request to main

2024-01-18 03:58 UTC, AngleSideAngle requested changes

2024-01-18 03:58 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/drive/TalonSwerveModule.java
> +
The turn motor configuration should be changed to be the same as FlexModule

2024-01-18 03:58 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/drive/TalonSwerveModule.java
> +public class TalonSwerveModule implements ModuleIO {
For naming consistency with `FlexModule`, this should be named `TalonModule`

2024-01-18 03:58 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/drive/TalonSwerveModule.java
> +public class TalonSwerveModule implements ModuleIO {
Also maybe add a line of javadoc describing what the class is

2024-01-19 14:30 UTC, merged